version: '3'
services:
  configuration-api.api.internal.bravehub-dev.com:
    build: configuration-api
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      BRAVEHUB_SUFFIX: "bravehub-dev.com"
      FLASK_DEBUG: 1
      FLASK_APP: src/app.py
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - ./configuration-api:/root/configuration-api:consistent
  logging-api.api.internal.bravehub-dev.com:
    build: logging-api
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      BRAVEHUB_SUFFIX: "bravehub-dev.com"
      FLASK_DEBUG: 1
      FLASK_APP: src/app.py
    ports:
      - "0.0.0.0:5010:5000"
    volumes:
      - ./logging-api:/root/logging-api
  provisioning-api.api.internal.bravehub-dev.com:
    build: provisioning-api
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      BRAVEHUB_SUFFIX: "bravehub-dev.com"
      FLASK_DEBUG: 1
      FLASK_APP: src/app.py
    ports:
      - "0.0.0.0:5020:5000"
    volumes:
      - ./provisioning-api:/root/provisioning-api
