---
- name: Setup awscli.
  include_role:
    name: aws
    tasks_from: awscli-configure

- name: Create the hbase user.
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: hbase
    uid: "{{hbase_uid}}"
    comment: "Hbase user."
    state: present
    group: docker
    home: "{{hbase_home}}"

- name: Obtain docker registry uri.
  become: yes
  become_user: root
  become_method: sudo
  shell: |
    . {{home_folder}}/instance-descriptor.sh && \
    echo ${DOCKER_REGISTRY}/${Env}
  register: instance_descriptor

- set_fact:
    DOCKER_REGISTRY_URI: "{{instance_descriptor.stdout}}"

- name: Copy the start script.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: home/hbase/start-hbase.sh.j2
    dest: "{{hbase_home}}/start-hbase.sh"
    owner: hbase
    mode: 0760

- name: Copy the stop script.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: home/hbase/stop-hbase.sh.j2
    dest: "{{hbase_home}}/stop-hbase.sh"
    owner: hbase
    mode: 0760

- name: Copy hbase site configuration file.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: home/hbase/hbase-site.xml.j2
    dest: "{{hbase_home}}/hbase-site-{{HBASE_ROLE}}.xml"
    owner: hbase
    mode: 0760
  when: HBASE_ROLE == "master" or HBASE_ROLE == "thrift"

- name: Determine the hbase regionserver hostname.
  include_role:
    name: shared-storage-setup
    tasks_from: server-hostname
  vars:
    SERVER_HOSTNAME_LOCK_FILE: "{{provisioning_storage}}/hbase-regionserver.lock"
    SERVER_HOSTNAME_FILE: "{{hbase_home}}/hbase-regionserver-hostname"
    SERVER_MAX_INSTANCES: "{{hbase_max_regionservers}}"
    SERVER_INVENTORY_FILE: "{{provisioning_storage}}/hbase-regionservers.json"
    SERVER_NAME_PATTERN: "{{hbase_regionserver_pattern}}.{{API_ZONE_NAME_STR}}"
  when: HBASE_ROLE == "regionserver"

- set_fact:
    hbase_regionserver_hostname: "{{SERVER_HOSTNAME}}"
  when: HBASE_ROLE == "regionserver"

- name: Determine the hbase thrift hostname.
  include_role:
    name: shared-storage-setup
    tasks_from: server-hostname
  vars:
    SERVER_HOSTNAME_LOCK_FILE: "{{provisioning_storage}}/hbase-thrift.lock"
    SERVER_HOSTNAME_FILE: "{{hbase_home}}/hbase-thrift-hostname"
    SERVER_MAX_INSTANCES: "{{hbase_max_regionservers}}"
    SERVER_INVENTORY_FILE: "{{provisioning_storage}}/hbase-thrift.json"
    SERVER_NAME_PATTERN: "{{hbase_thrift_pattern}}.{{API_ZONE_NAME_STR}}"
  when: HBASE_ROLE == "thrift"

- set_fact:
    hbase_thrift_hostname: "{{SERVER_HOSTNAME}}"
  when: HBASE_ROLE == "thrift"

- name: Store hbase regionserver dns entry.
  include_role:
    name: aws
    tasks_from: aws-setrecord.yml
  vars:
    DOMAIN_NAME: "{{hbase_regionserver_hostname}}"
  when: HBASE_ROLE == "regionserver" and hbase_regionserver_hostname

- name: Store hbase thrift dns entry.
  include_role:
    name: aws
    tasks_from: aws-setrecord.yml
  vars:
    DOMAIN_NAME: "{{hbase_thrift_hostname}}"
  when: HBASE_ROLE == "thrift" and hbase_thrift_hostname

- name: Copy hbase site regionserver configuration file.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: home/hbase/hbase-site.xml.j2
    dest: "{{hbase_home}}/hbase-site-regionserver.xml"
    owner: hbase
    mode: 0760
  when: HBASE_ROLE == "regionserver"

- name: Copy hbase regionservers configuration file.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: home/hbase/regionservers.j2
    dest: "{{hbase_home}}/regionservers"
    owner: hbase
    mode: 0760

- name: Determine the hbase master hostname.
  include_role:
    name: shared-storage-setup
    tasks_from: server-hostname
  vars:
    SERVER_HOSTNAME_LOCK_FILE: "{{provisioning_storage}}/hbase-master.lock"
    SERVER_HOSTNAME_FILE: "{{hbase_home}}/hbase-master-hostname"
    SERVER_MAX_INSTANCES: "{{hbase_max_masters}}"
    SERVER_INVENTORY_FILE: "{{provisioning_storage}}/hbase-masters.json"
    SERVER_NAME_PATTERN: "{{hbase_master_pattern}}.{{API_ZONE_NAME_STR}}"
  when: HBASE_ROLE == "master"

- set_fact:
    HBASE_MASTER_HOSTNAME: "{{SERVER_HOSTNAME}}"
  when: HBASE_ROLE == "master"

- name: Store hbase master dns entry.
  include_role:
    name: aws
    tasks_from: aws-setrecord.yml
  vars:
    DOMAIN_NAME: "{{HBASE_MASTER_HOSTNAME}}"
  when: HBASE_ROLE == "master" and HBASE_MASTER_HOSTNAME

- name: Create the hbase data storage.
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: "{{shared_storage}}/hbase"
    state: directory
    group: root
    owner: hbase
    mode: "u+rw,g+r,o-r"
  when: HBASE_ROLE == "master" and HBASE_MASTER_HOSTNAME

- name: Copy hbase master systemd script.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: etc/systemd/system/hbase.service.j2
    dest: /etc/systemd/system/hbase-master.service
  when: HBASE_ROLE == "master" and HBASE_MASTER_HOSTNAME

- name: Copy hbase regionserver systemd script.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: etc/systemd/system/hbase.service.j2
    dest: /etc/systemd/system/hbase-regionserver.service
  when: HBASE_ROLE == "regionserver" and hbase_regionserver_hostname

- name: Copy hbase thrift systemd script.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: etc/systemd/system/hbase.service.j2
    dest: /etc/systemd/system/hbase-thrift.service
  when: HBASE_ROLE == "thrift" and hbase_thrift_hostname

- pause:
    seconds: "{{wait_for_zookeepeer_seconds}}" # give zookeeper dns record enough time to propagate.
  when: HBASE_ROLE == "master" and HBASE_MASTER_HOSTNAME

- pause:
    seconds: "{{wait_for_zookeepeer_seconds}}" # give zookeeper dns record enough time to propagate.
  when: HBASE_ROLE == "regionserver" and hbase_regionserver_hostname

- pause:
    seconds: "{{wait_for_zookeepeer_seconds}}" # give zookeeper dns record enough time to propagate.
  when: HBASE_ROLE == "thrift" and hbase_thrift_hostname

- name: Authenticate hbase docker engine to all registries.
  become: yes
  become_user: root
  become_method: sudo
  include_role:
    name: docker-setup
    tasks_from: registry-auth
  vars:
    AUTH_HOME_DESTINATION: "{{hbase_home}}"
    AUTH_HOME_USER: hbase

- name: Activate hbase master service.
  become: yes
  become_user: root
  become_method: sudo
  systemd:
    daemon_reload: yes
    enabled: yes
    name: hbase-master
    state: restarted
  when: HBASE_ROLE == "master" and HBASE_MASTER_HOSTNAME

- name: Activate hbase regionserver service.
  become: yes
  become_user: root
  become_method: sudo
  systemd:
    daemon_reload: yes
    enabled: yes
    name: hbase-regionserver
    state: restarted
  when: HBASE_ROLE == "regionserver" and hbase_regionserver_hostname

- name: Activate hbase thrift service.
  become: yes
  become_user: root
  become_method: sudo
  systemd:
    daemon_reload: yes
    enabled: yes
    name: hbase-thrift
    state: restarted
  when: HBASE_ROLE == "thrift" and hbase_thrift_hostname
