---
- name: Obtain AWS_REGION.
  shell: curl http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/.$//'
  register: AWS_REGION
  tags:
    - router-setup
    - router-dns-setup

- name: Obtain API_ZONE_NAME.
  shell: . {{home_folder}}/instance-descriptor.sh && aws route53 get-hosted-zone --id ${API_ZONE_ID} | jq .HostedZone.Name | sed 's/\"//' | sed 's/\"//' | sed 's/.$//'
  register: API_ZONE_NAME
  tags:
    - router-setup
    - router-dns-setup

- name: Remove previously saved API_ZONE_NAME.
  shell: sed -i 's/export API_ZONE_NAME=.*//' {{home_folder}}/instance-descriptor.sh
  tags:
    - router-setup
    - router-dns-setup

- name: Persist API_ZONE_NAME.
  shell: echo "export API_ZONE_NAME={{API_ZONE_NAME.stdout}}" >> {{home_folder}}/instance-descriptor.sh
  tags:
    - router-setup
    - router-dns-setup

- name: Balance thrift servers.
  include_role:
    name: aws
    tasks_from: aws-dnsbalance
  vars:
    BALANCED_ROLE: "{{router_balanced_name}}"
    SERVER_TAGGED_ROLE: "{{router_instance_role}}"
  tags:
    - router-setup
