---
- name: Obtain AWS_REGION.
  shell: curl http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/.$//'
  register: AWS_REGION
  tags:
    - router-setup
    - router-dns-setup

- name: Obtain API_ZONE_NAME.
  shell: . {{home_folder}}/instance-descriptor.sh && aws route53 get-hosted-zone --id ${API_ZONE_ID} | jq .HostedZone.Name | sed 's/\"//' | sed 's/\"//' | sed 's/.$//'
  register: API_ZONE_NAME
  tags:
    - router-setup
    - router-dns-setup

- name: Remove previously saved API_ZONE_NAME.
  shell: sed -i 's/export API_ZONE_NAME=.*//' {{home_folder}}/instance-descriptor.sh
  tags:
    - router-setup
    - router-dns-setup

- name: Persist API_ZONE_NAME.
  shell: echo "export API_ZONE_NAME={{API_ZONE_NAME.stdout}}" >> {{home_folder}}/instance-descriptor.sh
  tags:
    - router-setup
    - router-dns-setup

- name: Obtain all routers ips.
  shell: export AWS_DEFAULT_REGION={{AWS_REGION.stdout}} && . {{home_folder}}/instance-descriptor.sh && aws ec2 describe-instances --filters "Name=tag:bravehub:layer,Values=routing-api-gateway" --filters "Name=tag:bravehub:stack,Values=${STACK_NAME}" --filters "Name=instance-state-name,Values=running" | jq -r '.Reservations[].Instances[].NetworkInterfaces[0].PrivateIpAddress'
  register: ROUTER_IPS
  tags:
    - router-setup
    - router-dns-setup

- name: Configure record set json input.
  template:
    src: "router-dns.json.j2"
    dest: "{{home_folder}}/router-dns.json"
  tags:
    - router-setup
    - router-dns-setup

- name: Upsert the internal router dns record set.
  shell: . {{home_folder}}/instance-descriptor.sh && aws route53 change-resource-record-sets --hosted-zone-id ${API_ZONE_ID} --change-batch file://{{home_folder}}/router-dns.json
  tags:
    - router-setup
    - router-dns-setup
