---
- name: Setup awscli.
  include_role:
    name: aws
    tasks_from: awscli-configure

- name: Obtain all {{BALANCED_ROLE}} server ips.
  shell: export AWS_DEFAULT_REGION={{AWS_REGION_STR}} && . {{home_folder}}/instance-descriptor.sh && aws ec2 describe-instances --filters "Name=tag:bravehub:layer,Values={{SERVER_TAGGED_ROLE}}" "Name=tag:bravehub:stack,Values=${STACK_NAME}" "Name=instance-state-name,Values=running" | jq -r '.Reservations[].Instances[].NetworkInterfaces[0].PrivateIpAddress'
  register: BALANCED_IPS_PRIVATE
  when: PUBLIC_DNS is not defined or not PUBLIC_DNS

- name: Obtain all {{BALANCED_ROLE}} public server ips.
  shell: |
    export AWS_DEFAULT_REGION={{AWS_REGION_STR}} && \
    . {{home_folder}}/instance-descriptor.sh && \
    aws ec2 describe-instances --filters "Name=tag:bravehub:layer,Values={{SERVER_TAGGED_ROLE}}" "Name=tag:bravehub:stack,Values=${STACK_NAME}" "Name=instance-state-name,Values=running" | jq -r '.Reservations[].Instances[].NetworkInterfaces[0].PrivateIpAddresses[0].Association.PublicIp'
  register: BALANCED_IPS_PUBLIC
  when: PUBLIC_DNS is defined and PUBLIC_DNS

- set_fact:
    BALANCED_IPS: "{% if PUBLIC_DNS is defined and PUBLIC_DNS %}{{BALANCED_IPS_PUBLIC}}{% else %}{{BALANCED_IPS_PRIVATE}}{% endif %}"

- name: Configure {{BALANCED_ROLE}} record set json input.
  template:
    src: "servers-dns.json.j2"
    dest: "{{home_folder}}/{{BALANCED_ROLE}}-dns.json"

- name: Upsert the internal {{BALANCED_ROLE}} dns record set.
  shell: |
    . {{home_folder}}/instance-descriptor.sh && \
    aws route53 change-resource-record-sets \
      --hosted-zone-id ${API_ZONE_ID} \
      --change-batch file://{{home_folder}}/{{BALANCED_ROLE}}-dns.json
  when: PUBLIC_DNS is not defined or not PUBLIC_DNS

- name: Upsert the public {{BALANCED_ROLE}} dns record set.
  shell: |
    . {{home_folder}}/instance-descriptor.sh && \
    aws route53 change-resource-record-sets \
      --hosted-zone-id ${API_ZONE_PUBLIC_ID} \
      --change-batch file://{{home_folder}}/{{BALANCED_ROLE}}-dns.json
  when: PUBLIC_DNS is defined and PUBLIC_DNS
