---
- name: Setup awscli.
  include_role:
    name: aws
    tasks_from: awscli-configure

- name: Obtain all {{BALANCED_ROLE}} server ips.
  shell: export AWS_DEFAULT_REGION={{AWS_REGION.stdout}} && . {{home_folder}}/instance-descriptor.sh && aws ec2 describe-instances --filters "Name=tag:bravehub:layer,Values={{SERVER_TAGGED_ROLE}}" "Name=tag:bravehub:stack,Values=${STACK_NAME}" "Name=instance-state-name,Values=running" | jq -r '.Reservations[].Instances[].NetworkInterfaces[0].PrivateIpAddress'
  register: BALANCED_IPS

- name: Configure {{BALANCED_ROLE}} record set json input.
  template:
    src: "servers-dns.json.j2"
    dest: "{{home_folder}}/{{BALANCED_ROLE}}-dns.json"

- name: Upsert the internal thrift dns record set.
  shell: . {{home_folder}}/instance-descriptor.sh && aws route53 change-resource-record-sets --hosted-zone-id ${API_ZONE_ID} --change-batch file://{{home_folder}}/{{BALANCED_ROLE}}-dns.json
