---
- name: Add aws package.
  become: yes
  become_user: root
  become_method: sudo
  apt:
    name: awscli
    state: present
  tags:
    - aws

- name: Add jq package.
  become: yes
  become_user: root
  become_method: sudo
  apt:
    name: jq
    state: present
  tags:
    - aws
