---
- name: Hbase common setup.
  include_role:
    name: hbase
    tasks_from: hbase-common
  vars:
    HBASE_ROLE: thrift
  tags:
    - hbase-thrift-setup

- name: Balance thrift servers.
  include_role:
    name: aws
    tasks_from: aws-dnsbalance
  vars:
    BALANCED_ROLE: "{{hbase_thrift_balanced_name}}"
    SERVER_TAGGED_ROLE: "{{hbase_thrift_instance_role}}"
  tags:
    - hbase-thrift-setup
