---
- name: Setup awscli.
  include_role:
    name: aws
    tasks_from: awscli-configure
  tags:
    - bravehub-db-setup

- name: Obtain the hbase site configuration.
  become: yes
  become_user: root
  become_method: sudo
  shell: base64 "{{hbase_home}}/hbase-site-master.xml"
  register: HBASE_SITE_CONFIG
  tags:
    - bravehub-db-setup

- set_fact:
    HBASE_SITE_CONFIG: "{{HBASE_SITE_CONFIG.stdout}}"

- name: Obtain docker registry uri.
  become: yes
  become_user: root
  become_method: sudo
  shell: |
    . {{home_folder}}/instance-descriptor.sh && \
    echo ${DOCKER_REGISTRY}/${Env}
  register: instance_descriptor
  tags:
    - bravehub-db-setup

- set_fact:
    DOCKER_REGISTRY_URI: "{{instance_descriptor.stdout}}"

- name: Run the setup db docker image.
  become: yes
  become_user: docker
  become_method: sudo
  shell: |
      docker run -e "HBASE_SITE_CONFIG={{HBASE_SITE_CONFIG}}" \
        -e "SCRIPT_NAME=~/scripts/hbase/00-create-data-model.txt" \
        {{DOCKER_REGISTRY_URI}}/setup-database:{{bravehub_version}}
  tags:
    - bravehub-db-setup
